.travis.yml
README.md
glide.lock
glide.yaml
main.go
tablewriter.go
trdsql.go

Added ASCII Table & Markdown using https://github.com/olekukonko/tablewriter

ASCII Table & MarkDown support(tablewriter)

---

database.go
database_test.go
inout.go
ltsv.go
trdsql.go

PostgreSQL changed Import from INSERT to COPY.

Change to process within transaction.

---

csv.go
database.go
database_test.go
inout.go
json.go
ltsv.go
raw.go
tablewriter.go
vertical.go

Import as much as possible at once
fix errcheck

Further speed up

---

README.md
csv.go
csv_test.go
database.go
database_test.go
inout.go
json.go
ltsv.go
main.go
tablewriter.go
trdsql.go

Fix by check of gometalinter.
Rename function name.

Refactoring

---

README.md
_example/import/main.go
_example/simple/main.go
cmd/cmd.go
exporter.go
exporter_test.go
importer.go
importer_test.go
input_csv.go
input_json.go
input_ltsv.go
output_csv.go
output_json.go
output_ltsv.go
output_raw.go
output_tablewriter.go
output_tbln.go
output_vertical.go
reader.go
trdsql_test.go
writer.go

Rewrite with Functional Option Pattern to make
ReadOpts/WriteOpts optional.

Rewrite with Functional Option Pattern

---

README.md
_example/import/test.csv
_example/simple/main.go
_example/slice/main.go
example_test.go
importer.go
importer_slice.go
importer_test.go
input_slice.go
input_slice_test.go
output_slice.go
output_slice_test.go
reader.go
trdsql.go
trdsql_test.go

Added go slice to import/export.

Add slice read / writer

---

cmd/cmd.go
importer_slice.go
input_slice.go
input_slice_test.go
output_slice.go
trdsql_json1_test.go
writer.go

Add comment

---

_example/buffer/main.go
example_test.go
importer.go
importer_buffer.go
importer_buffer_test.go
importer_slice.go
importer_slice_test.go
importer_test.go
reader.go

BufferImporter imports from io.Reader.
Mostly using default importer function.
Add test and example.

Add BufferImporter

---

input_slice.go
input_slice_test.go

Currently, only int type is reflected in Database type.

Enable data type for SliceReader

---

.travis.yml
go.mod
go.sum
input_slice.go
version.go

Improvement of SliceReader

---

database.go

Support empty values (not an error for tbln format).

Skip when empty read

---

importer.go
importer_test.go

Rename listTable to TableNames and change to public function.

Rename listTable to TableNames

---

.travis.yml
Makefile
README.md
cmd/cmd.go
go.mod
go.sum
version.go

Change to embed version with ldflags

---

importer.go
importer_test.go

Changed to SQLFields to be a public function
so that sqlFields can be called from outside.

Changed sqlFields to public function

---

importer.go
trdsql_test.go

Removed the symbol to the right of the extension.

Supported escaped file names

---

database.go
go.mod
go.sum
input_csv.go
input_csv_test.go
input_json.go
input_ltsv.go
input_tbln.go
reader.go
trdsql_test.go

Reverse order to get had been set a value for the bulk insert,
when using the preread. Fixed in order of reading.
Make errors in database errors.new constant.

Fixed INSERT order changing when using bulk insert

---

database.go

Fixed the writing method that does not affect the operation.
Modify the format.

Improved comments

---

database.go

Change the error message and error name to correct

---

cmd/cmd.go

Fixed that config was enabled.

Enable command option rather than config

---

Makefile

Embed the version with ldflags only when checking out from git.

Improved version embedding.

---

README.md

I set up Automated builds on Docker Hub,
so I added a procedure to docker pull.
fix #96.

Add Docker pull procedure

---

database.go
input_csv.go
input_ltsv.go
reader.go

Other refactoring.
Move function position.

Move skipRead to reader.go

---

cmd/cmd.go
cmd/cmd_test.go

Remove space before and after SQL.
Remove SQL semicolon.

Improve SQL trim

---

.github/workflows/test.yml
database_test.go
importer_test.go
trdsql_test.go

Changed to get dsn at test from environment variable.

Add test using database service with github actions

---

exporter.go
output_ltsv.go

Improved ltsv output speed

---

output_raw.go
output_raw_test.go

Improved raw output speed.
Renamed variable sep to delimiter.

Improved raw output

---

README.md
cmd/cmd.go

Changed usage output to customized instead of flag default.
Improved help messages.

Improved usage

---

input_ltsv.go

If isPrefix is true, read again.
Resolve #132

Supported long line of LTSV

---

output_json.go
output_json_test.go
output_jsonl.go

If json.Unmarshal is possible,
it is converted to json.RawMessage and returned.

Improve the handling of json

---

analyze.go
cmd/cmd.go
go.mod
go.sum
importer.go
importer_test.go
reader.go
trdsql.go

Organized the code to guess readOpts from the filename.

Added discrimination by extension of tsv and psv

---

analyze.go

It was not reflected in the table name of analyze when using path.

Fixed table name analyzed when using path

---

input_json.go

Avoid mapping to float64 in json

---

README.md

Added freebsd package link

---

database.go
go.mod
go.sum

Changed to use range as much as possible in the for statement
(Refactoring).

Changed the for statement to use range

---

Dockerfile

Changed to the image of go1.17.

Changed docker image to multi-stage builds

---

analyze.go
cmd/cmd.go
database.go
exporter.go

Suggest options if json or ltsv is interpreted as csv. 
Suggest options for jq if json is nested.

Improved analyze additional advice

---

cmd/cmd.go
go.mod
go.sum
importer.go
input_gw.go
input_gw_test.go
reader.go
testdata/dpkg.txt
testdata/ps.txt
trdsql.go

Used https://github.com/noborus/guesswidth
to accept width specification format.
It supports formats with specified widths,
such as the output of many types of `ps`.

Added width specification format to input format

---

README.md

Add ndjson as a supplement

---

input_yaml.go
input_yaml_test.go

Enable UseOrderedMap.
However, gojq is not supported, so disable it.

Enable orderedmap when not using jq

---

output_yaml.go

If it is a yaml string, encode the yaml string and then output.

Output with yaml when data is yaml

---

input_yaml.go

YAML not reversible with OrderedMap enabled.

Disable OrderedMap

---

input_yaml.go
output_vertical.go

Remove trailing newlines in yaml input, not output.

Remove trailing newline in yaml input

---

input_yaml.go
trdsql_test.go

Cleaned up input YAML functions and added comments. Added YAML to the benchmark.

Refactored YAML input

---

README.md

Added YAML section

---

cmd/cmd.go
cmd/cmd_test.go

Added option to specify table name instead of query.

Added option to specify table name

---

importer.go
input_csv.go
reader.go
trdsql.go

Reader can now be registered externally.
Register the extension and reader creation function.

Reader can be registered externally

---

importer.go

Allow `SELECT*FROM table`.
Improved string concatenation.

Expand statements allowed in SQL

---

README.md

Add link to the README.md

---

.github/workflows/release.yml

Fixed that the version of upload-artifact did not match.

Fixed that the version of upload-artifact

---

output_csv.go
output_ltsv.go
output_raw.go

Improved the use of `if` statements for the first column when outputting delimiters.

Reduce `if` statements in loops

---

cmd/root.go

Some flags should have returned early.
Reviewed lint findings.

Fixes that should have been returned early

---

cmd/cmd.go
input_text.go
input_text_test.go
reader.go
trdsql.go
trdsql_test.go

Add Text Format, which has 1 Column per line.

Add Text Format.
