database.go
database_test.go
importer.go

Quote is preferred because it is a quoted character.
Change EscapeName to QuotedName and call it from others.

Renamed from escape to quote

---

exporter.go
output_tbln.go

The column containing '\n' was replaced with '\\n'.
However, replacing all the output is not the desired result
(especially raw output), so change it to tbln output only.

Improved output of columns with line breaks

---

importer.go

Wrap os.Stdin with bufio.NewReader (and ioutil.NopCloser).
There was large data that could be imported successfully in the file
but failed in stdin(when using sqlite3).
Change to use bufio.NewReader to stabilize input from os.Stdin.

Wrap os.Stdin with bufio.NewReader (Fix #83).

---

input_csv.go
input_csv_test.go

Stop setting TrimLeadingSpace = true when the delimiter is not space.
Setting TrimLeadingSpace to true removes unicode.IsSpace as well as space.
This is not the intended behavior.

Change TrimLeadingSpace set conditions (Fix #84).

---

cmd/cmd.go

Use args[0] for the command name(re-change).

Enclose arguments in double quotes if necessary

---

analyze.go

Regular expressions had to check only lowercase letters, _, and numbers,
and also reserved words.

revert the checking regular expression.

---

importer.go
importer_test.go

Added check for table name not in list to replace.
Tables that did not successfully import the file
did not need to be replaced in the first place.

Fixed generate_series (1,10) error in FROM clause

---

analyze_test.go
input_csv.go
input_csv_test.go
input_json_test.go
input_ltsv.go
input_ltsv_test.go
input_tbln.go
input_tbln_test.go

Migrated old test to Table Driven Test.
Made the behavior of New*Reader as consistent as possible.
Supports formats without TBLN name or type specification.

Improved testing

---

importer.go

Parentheses is used in functions in the FROM clause
and in the WITH clause.

Added' (' and')' as SQL clause separator

---

README.md
cmd/cmd.go
completion/trdsql-completion.zsh
database.go
exporter.go
output_csv.go
output_csv_test.go
testdata/test_quote.csv
testdata/test_quote2.csv
trdsql_test.go
writer.go
writer_test.go

Remove use of encoding/csv, and output CSV in writer.
Added option to specify quote character.
Option to set CRLF at the end of line.
CSV output performance has been improved.

Added option to quote all columns with quotes(#33)

---

importer.go

Added support for the TABLE command(PostgreSQL and MySQL only).
Allowed `TABLE test. csv` instead of `SELECT * FROM test. csv`.

Added support for the TABLE command

---

README.md
cmd/cmd.go
output_tablewriter.go
writer.go

The default for tablewriters is to insert a line break
in the middle of a column, but this can be changed
with an option.

Added an option to enable/disable autowrap with tablewriter

---

cmd/cmd.go
database.go
exporter.go
importer.go
trdsql.go
writer.go

* Changed the query to database to use with context.
* Functions with Context are added to NewTRDSQL, NewImporter
and NewExporter.
* Changed public Table struct to private importTable struct.
* Stopped running db.stmtClose with defer.
Since it is not canceled at context.Cancel, it is closed only
when it is normal.

Added Context support

---

README.md

- The `-v` option needs to separator (`:`)

README: fix the option value of "docker run"

---

exporter.go

The reason why "json_extract doesn't output anything on error" in #161
was due to the omission of check in rows.Err().

Fixed missing check in rows.Err()

---

README.md

I got errors below when trying [4.10. JSON](https://github.com/noborus/trdsql#410-json) sample in `README.md`.
```
$ cat sample2.json
[
{
"id": 1,
"name": "Drolet",
"attribute": { "country": "Maldives", "color": "burlywood" }
},
{
"id": 2,
"name": "Shelly",
"attribute": { "country": "Yemen", "color": "plum" }
},
{
"id": 3,
"name": "Tuck",
"attribute": { "country": "Mayotte", "color": "antiquewhite" }
}
]
$ trdsql -ijson "SELECT id, name, JSON_EXTRACT(attribute,'$country'), JSON_EXTRACT(attribute,'$color') FROM sample2.json"
```
Using SQLite3 driver:
```
2022/11/19 07:04:22 export: JSON path error near ''
```
Using MySQL driver:
```
2022/11/19 07:04:46 export: Error 3143 (42000): Invalid JSON path expression. The error is around character position 0.
```
The correct SQL is probably here. …

Fixed JSON sample in README

---

cmd/cmd.go
importer.go
input_yaml.go
output_yaml.go
reader.go
trdsql.go

It simply interprets yaml as a table.
Implements #217.

Added yaml import

---

.github/workflows/test.yml
input_yaml.go

Prevents panic, but just displays an error instead of panic. This is for issue https://github.com/goccy/go-yaml/issues/373, so it may be removed if go-yaml is updated.

Preventing panic due to invalid yaml file

---

database.go
database_connect.go
database_connect_cgo.go

Fixed INSERT failure when number of columns is greater than maxBulk. Increased maxBulk to 1000.

Fixed INSERT failure when there are many columns

---

reader.go

The delimiter was not automatically set for TSV/PSV (it worked only when the delimiter was specified).

Fixed automatic determination of TSV/PSV

---

cmd/cmd.go

This typo was noticed by Stuart Henderson
See: https://marc.info/?l=openbsd-ports&m=171992964702902&w=2

Fixed a typo in examples

---

README.md
reader.go

Add support for determining text format by extension. 
Add text format description to README.md.

Add extension support for text format

---

database.go
exporter.go
input_csv.go
input_json.go
input_ltsv.go
input_tbln.go
input_yaml.go

- Replace debug.Printf(query) with debug.Printf("%s", query)
- Replace debug.Printf(err.Error()) with debug.Printf("%s", err.Error())
- Ensures consistent and safe debug output formatting

fix: use debug.Printf("%s", ...) for all debug output
